// @ts-nocheck
// All UI strings — English (en, primary) and Spanish (es)

const STRINGS = {
  en: {
    heroSubtitle: "Your Wisconsin summer trip guide — lakes, trails, boats &amp; more",
    searchPlaceholder: 'Try "salsa dancing with my partner" or "easy waterpark for kids"…',
    searchBtn: "Find for me",
    searchClear: "Clear ×",
    filterAll: "All",
    filterOutdoor: "🌊 Lake &amp; Outdoor",
    filterKids: "🏊 Kids &amp; Pools",
    filterDancing: "💃 Dancing",
    filterFriends: "🎉 Friends Trip",
    filterFirst: "🌟 First Timers",
    sortLabel: "Sort by",
    sortDefault: "Default order",
    sortRating: "Highest rated",
    sortActivities: "Most activities",
    sortEasiest: "Easiest first",
    sortHardest: "Hardest first",
    vibeLabel: "What's your vibe today?",
    vibeOutdoor: "🌊 Lake Day",
    vibeKids: "🏊 Family Fun",
    vibeDancing: "💃 Night Out",
    vibeFriends: "🎉 With Friends",
    featuredEyebrow: "⭐ Featured today",
    catOutdoor: "🌊 Lake &amp; Outdoor",
    catKids: "🏊 Kids &amp; Pools",
    catDancing: "💃 Dancing",
    catFriends: "🎉 Friends Trip",
    catFirst: "🌟 First Timer's Must-Sees",
    seeAll: "See all &#8599;",
    subLatin: "🌎 Latin American",
    subOther: "🎵 Other Styles",
    cardMap: "View on Map &#8599;",
    cardRate: "&#9733; Rate &amp; Comment",
    cardSave: "Save to my trip",
    cardUnsave: "Saved — remove",
    firstTimerBadge: "🌟 Must See",
    insightsTitle: "Insights",
    statDests: "destinations",
    statAvg: "avg rating",
    statTop: "Top activity:",
    statTags: "avg tags / dest",
    freqTitle: "Activity Distribution",
    tipsTitle: "Quick Tips",
    tips: [
      "🕐 <strong>Best time:</strong> Late June–August; July has warmest lake temps (70°F+). Book 4–6 weeks ahead.",
      "⛵ <strong>Renting a boat:</strong> Bring a valid ID; pontoons run $80–$200/day at most marinas.",
      "👨‍👩‍👧 <strong>With kids:</strong> Pack sunscreen, life jackets, and check if beaches have lifeguards.",
      "🏕️ <strong>Hiking:</strong> Wear layers, bring bug spray, and download AllTrails offline maps.",
      "🎣 <strong>Fishing license:</strong> Required for ages 16+; 1-day non-resident ~$10 at wildlifelicense.com/wi.",
      "🌟 <strong>Hidden gem:</strong> Visit Tue–Thu for quieter beaches and easier boat rentals.",
    ],
    footerMain: "Summer Vibes Wisconsin &mdash; Trip Guide 2026",
    footerSub: "Always check state park websites for current hours and reservation requirements before you go.",
    recoTitle: "You Might Also Like",
    communityTitle: "Community Rating",
    noRatings: "No ratings yet — be the first!",
    rateTitle: "Rate This Place",
    commentTitle: "Leave a Comment",
    commentNamePh: "Your name (optional)",
    commentBodyPh: "Share your experience at this place...",
    commentSubmit: "Post Comment",
    commentsTitle: "What Travelers Say",
    commentsLoading: "Loading...",
    commentsEmpty: "No comments yet. Share your experience!",
    ratingThanks: "Thanks for your rating!",
    ratingError: "Could not save rating. Try again.",
    searchNoResults: 'No matches — try "salsa", "kayak", "kids", or "friends trip"',
    searchNoResultsText: "No destinations matched. Try different words.",
    explore: "Explore &#8599;",
    savedCount: "saved to my trip",
    printBtn: "🖨️ Print itinerary",
    printTitle: "My Wisconsin Summer Trip",
    daySun: "Sunday Pick",
    dayMon: "Today's Pick",
    dayTue: "Today's Pick",
    dayWed: "Midweek Pick",
    dayThu: "Thursday Pick",
    dayFri: "Friday Pick",
    dayFriNight: "Friday Night Pick",
    daySat: "Saturday Pick",
    dayEvening: "Tonight's Pick",
  },

  es: {
    heroSubtitle: "Tu guía de verano en Wisconsin — lagos, senderos, lanchas y más",
    searchPlaceholder: 'Prueba "salsa con mi pareja" o "parque acuático fácil para niños"…',
    searchBtn: "Encuéntrame algo",
    searchClear: "Limpiar ×",
    filterAll: "Todo",
    filterOutdoor: "🌊 Lagos y Naturaleza",
    filterKids: "🏊 Niños y Albercas",
    filterDancing: "💃 Baile",
    filterFriends: "🎉 Viaje con Amigos",
    filterFirst: "🌟 Imperdibles",
    sortLabel: "Ordenar por",
    sortDefault: "Orden predeterminado",
    sortRating: "Mejor calificado",
    sortActivities: "Más actividades",
    sortEasiest: "Más fácil primero",
    sortHardest: "Más difícil primero",
    vibeLabel: "¿Cuál es tu plan de hoy?",
    vibeOutdoor: "🌊 Día de Lago",
    vibeKids: "🏊 Diversión Familiar",
    vibeDancing: "💃 Noche de Baile",
    vibeFriends: "🎉 Con Amigos",
    featuredEyebrow: "⭐ Destacado de hoy",
    catOutdoor: "🌊 Lagos y Naturaleza",
    catKids: "🏊 Niños y Albercas",
    catDancing: "💃 Baile",
    catFriends: "🎉 Viaje con Amigos",
    catFirst: "🌟 Imperdibles para tu Primer Viaje",
    seeAll: "Ver todos &#8599;",
    subLatin: "🌎 Latinoamérica",
    subOther: "🎵 Otros Estilos",
    cardMap: "Ver en Mapa &#8599;",
    cardRate: "&#9733; Calificar",
    cardSave: "Guardar en mi viaje",
    cardUnsave: "Guardado — quitar",
    firstTimerBadge: "🌟 Imperdible",
    insightsTitle: "Estadísticas",
    statDests: "destinos",
    statAvg: "calificación promedio",
    statTop: "Top actividad:",
    statTags: "tags promedio / destino",
    freqTitle: "Distribución de Actividades",
    tipsTitle: "Consejos Rápidos",
    tips: [
      "🕐 <strong>Mejor época:</strong> De junio a agosto; julio tiene las temperaturas más cálidas del lago (70°F+). Reserva con 4–6 semanas de anticipación.",
      "⛵ <strong>Rentar una lancha:</strong> Trae una ID válida; los pontones cuestan $80–$200 por día en la mayoría de los muelles.",
      "👨‍👩‍👧 <strong>Con niños:</strong> Lleva bloqueador solar, chalecos salvavidas y verifica si la playa tiene salvavidas.",
      "🏕️ <strong>Senderismo:</strong> Usa ropa en capas, lleva repelente y descarga los mapas de AllTrails sin conexión.",
      "🎣 <strong>Licencia de pesca:</strong> Requerida para mayores de 16 años; un día no residente ~$10 en wildlifelicense.com/wi.",
      "🌟 <strong>Tip secreto:</strong> Visita de martes a jueves para playas más tranquilas y rentas de lancha más fáciles.",
    ],
    footerMain: "Summer Vibes Wisconsin &mdash; Guía de Viaje 2026",
    footerSub: "Siempre verifica los horarios y requisitos de reserva en los sitios web de los parques estatales antes de ir.",
    recoTitle: "También Te Puede Gustar",
    communityTitle: "Calificación Comunitaria",
    noRatings: "Sin calificaciones — ¡sé el primero!",
    rateTitle: "Califica Este Lugar",
    commentTitle: "Deja un Comentario",
    commentNamePh: "Tu nombre (opcional)",
    commentBodyPh: "Comparte tu experiencia en este lugar...",
    commentSubmit: "Publicar",
    commentsTitle: "Lo Que Dicen los Viajeros",
    commentsLoading: "Cargando...",
    commentsEmpty: "Sin comentarios todavía. ¡Comparte tu experiencia!",
    ratingThanks: "¡Gracias por tu calificación!",
    ratingError: "No se pudo guardar. Inténtalo de nuevo.",
    searchNoResults: 'Sin resultados — prueba "salsa", "kayak", "niños" o "amigos"',
    searchNoResultsText: "Ningún destino coincide. Intenta con otras palabras.",
    explore: "Explorar &#8599;",
    savedCount: "lugar(es) en mi viaje",
    printBtn: "🖨️ Imprimir itinerario",
    printTitle: "Mi Viaje a Wisconsin",
    daySun: "Recomendación del Domingo",
    dayMon: "Plan del Día",
    dayTue: "Plan del Día",
    dayWed: "Pick de Entre Semana",
    dayThu: "Plan del Jueves",
    dayFri: "Plan del Viernes",
    dayFriNight: "Noche de Viernes",
    daySat: "Plan del Sábado",
    dayEvening: "Plan de Esta Noche",
  },
};
